### PR TITLE
Feature install with config

### PR DESCRIPTION
**Pull request by Fasse**
#174

### CODE REVIEW

**Comment by Fasse** [comment]
Will someone review this?

**Comment by Bullnados** [comment]
What should be the correct behavior? I created empty config. than error message appeared that the dates didnt match.

**Comment by ximex** [comment]
fast look on the code looks good. no tests done.

**Comment by Fasse** [comment]
@Bullnados which Dates doesn't match? What do you mean with empty config? The config Must be filled with your database login data.

**Comment by Bullnados** [comment]
Copied branch to webspace
Created an empty config.php in adm_my_files
Go to domain.tld/admidio
And follow instructions
After inserting database name database password etc. I got an admidio error message, that the dates doesn't match. If it still unclear i post a screenshot later

**Comment by Fasse** [comment]
Ok, that scenario is not in our focus. This pull request handle a Filled Config.php 
Where do a user got an empty config?

**Pull request merged**
