### PR TITLE
admStrTo-Upper/Lower to mb_strto-upper/lower

### PR DESCRIPTION
**Pull request by ximex**
isn't need anymore with PHP min version 5.3.7

https://secure.php.net/manual/en/function.mb-internal-encoding.php
https://secure.php.net/manual/en/function.mb-strtolower.php
https://secure.php.net/manual/en/function.mb-strtoupper.php

### CODE REVIEW

**Comment by Fasse** [comment]
The problem of this function was/is that not every browser support multibyte string. As far as I know multibyte extension is not a php default extension. First we implement the mb_strtolower functions and then there were error reports that this is not working. Therefore we implement the function in *string.php*.

Because of this I would not remove this functions.

**Comment by ximex** [comment]
mehhh... i hate this php extension system...
but maybe we should set mb_internal_encoding

**Comment by Fasse** [comment]
I hate it too. In my opinion there should be 1 php version with a defined set of function/classes ...
What do you mean with maybe we should set mb_internal encoding?

**Comment by ximex** [comment]
set it global: https://github.com/Admidio/admidio/commit/3aa6082c76250c712ae3478fdae585d1da5d1330

**Comment by Fasse** [comment]
But this would return an error if you havn't installed the multibyte extension.

**Comment by ximex** [comment]
oh... yes... you are right...

**Pull request closed without merging**
