### PR TITLE
set hashcost preference by benchmark

### PR DESCRIPTION
**Pull request by ximex**
please check if my logic is correct! didn't tested it ;-)

### CODE REVIEW

**Comment by Fasse** [comment]
Please open an issue and describe what you want to do with this code. At the moment I don't know what this is for?!?

**Comment by Fasse** [comment]
Now I have found the time to get familiar with the cost parameter of password_hash. One thing should be considered. The passwort_compat page says that the cost parameter has a range from 4 to 31. We should escape the loop if we reach a cost of 31. And we should begin with cost 4 not with 8 if there is old hardware or something else.

**Comment by Fasse** [comment]
Maybe we should still start with 8 so we do not have to many loops.

**Comment by ximex** [comment]
the loops are not the problem. the first loops would only take less than 20ms.
But i think, that even slow server should have a minimum cost of 8. but i could change this.

**Comment by Fasse** [comment]
The code looks good some minor comments:
- we should declare the globals at the beginning of the method so everyone see which global is already registered and used.
- some code comments would be nice to explain in a short sentence whats going on, especially in update.php and installation.php

**Comment by ximex** [comment]
hope this changes are ok

**Pull request merged**
