### PR TITLE
Feature safeurl

### LINKED ISSUE #664: Add function to build safe urls
add a function to build safe urls where all params are urlencoded and the full string is encoded to put it save in html code

### PR DESCRIPTION
**Pull request by ximex**
fixes #664

### CODE REVIEW

**Comment by ximex** [comment]
I'm finished here. Please review

**Comment by ximex** [comment]
@Fasse please test now. I think i found where the problem is.
If you we don't found url errors now i will switch the escape flag back to true and look at the special cases with the errors

**Comment by Fasse** [comment]
Still the same error. Did you have done an update successful?

**Comment by ximex** [comment]
@Fasse found the stupid bugs. Please test and merge if all is ok

**Pull request merged**
