### PR TITLE
Dockerfile improvements

### PR DESCRIPTION
**Pull request by schast**
* Add docker usage help to README.md
* create README-Docker.md with detailed docker usage help

Dockerfile improvments:
* Add healthcheck
* Install postfix to support mail delivery
* Install trivy to scan for security issues during image build
* Add build lables
* Add many configuration variables
* Add custom dockerhub build hook

### CODE REVIEW

**Comment by ximex** [comment]
The header image in the README.md isn't visible as it is white

**Comment by Fasse** [comment]
Maybe we should not make a subtitle to installation and update. We should add a new section for docker maybe after ##update and add there the docker content. 

You add some subfolders for docker `dockerscript` and `hooks` . Are they really necessary? Must we deliver these folders or could we add the files into a subfolder of the existing folders?

**Comment by Fasse** [comment]
btw there is also a `admidio_logo_black_200.png` and `admidio_logo_darkblue_200.png` in the images folder.

**Comment by schast** [comment]
> Maybe we should not make a subtitle to installation and update. We should add a new section for docker maybe after ##update and add there the docker content.
> 
> You add some subfolders for docker `dockerscript` and `hooks` . Are they really necessary? Must we deliver these folders or could we add the files into a subfolder of the existing folders?

The `dockerscript` folder can be moved anywhere. Any suggestions?

The `hooks` folder can not be moved, since it must be relative to the Dockerfile and overwrite the dockerhub basic build command. The `hooks` folder does not need to be delivered.

**Comment by Fasse** [comment]
Ok, than we should add the `hooks` to `.gitattributes` so we don't deliver that folder like `demo_data`.

The `dockerscript` would be perfect in `adm_program/system` but if you think it's to deep and hidden, we can add it just to `adm_program`.

It would be nice if you add one or two sentence at the beginning of the docker section in the readme. Something like 

> Admidio could also be used within a docker enviroment. Therefore we deliver a Dockerfile and you can easily setup your own docker image with the following command:

Also we could add a hint to https://hub.docker.com/r/admidio/admidio/ where they can find docker images.

**Comment by schast** [comment]
I don't think the right place for `dockerscripts` is in `adm_program/system` or in `adm_program` since it should only contains the admidio application code.
But the `dockerscripts` are only for docker administration.
Would it be sufficient to include `dockerscripts` also in .gitattributes?

**Comment by Fasse** [comment]
> Would it be sufficient to include `dockerscripts` also in .gitattributes?
If so than we wouldn't deliver these script with our download package and we could only link to those scripts in our doku or readme. If it's ok for you than we could do it. 

I don't want to deliver a new folder because users then have another folder that they must have to look for and update this folder ...

**Comment by schast** [comment]
I think in the ZIP delivery the Docker components do not need to be provided.

Maybe it would be nice to add the docker help also in the admidio wiki (https://www.admidio.org/dokuwiki/doku.php?id=de:2.0:installation)?

**Comment by Fasse** [comment]
Yes, it would be nice to have a docker page in our wiki. 

You can register at the wiki and send me your username. I will than give you the rights.

**Pull request merged**
