### PR TITLE
Use PDO class for database communication

### PR DESCRIPTION
**Pull request by Fasse**
@ximex please review my code

### CODE REVIEW

**Comment by Fasse** [comment]
@ximex please have a look at travis. I cant find the resolution to fix this.

**Comment by ximex** [comment]
i think the problems are from the merges of master.
If you want to update a "feature" branch to the changes of master, it is better to do a rebase than a merge.
I will look at it.

**Comment by Fasse** [comment]
No the conflicts are history. I could fix them with the merge. Dont know why this is in the comment.

The Problem with travis is also in the branch since several Versions.

**Comment by ximex** [comment]
found it! look at the missing space
```php
return trim($this->pdo->quote($string),"'");
```
to
```php
return trim($this->pdo->quote($string), "'");
```
pushed some other little improvements

**Pull request merged**
