### PR TITLE
Extract rendering to smarty

### PR DESCRIPTION
**Pull request by marchorst**
Related to: https://github.com/Admidio/admidio/issues/1304
Would be great if you can check which parts I have missed so far.
Thanks,
Marc

### CODE REVIEW

**Comment by Fasse** [comment]
I'm at holiday and will have a look to your changes in two weeks.

**Comment by Fasse** [comment]
Now I had time to look at your changes. It looks very good, but I found some minor issues:

- Date fields now show the date additionally over the field (view birthday field within profiles)
- Also the date now have the max width and not their special width as before
- Within the event dialog the date and time fields are not separated anymore. Its now one field.
- The red "required" bubble at checkbox fields will not be shown. View profile checkbox ** Ich willige in die Verarbeitung der Daten ein. **

**Review by Fasse — CHANGES_REQUESTED** [review]
Now I had time to look at your changes. It looks very good, but I found some minor issues:

   -  Date fields now show the date additionally over the field (view birthday field within profiles)
   - Also the date now have the max width and not their special width as before
   - Within the event dialog the date and time fields are not separated anymore. Its now one field.
   - The red "required" bubble at checkbox fields will not be shown. View profile checkbox ** Ich willige in die Verarbeitung der Daten ein. **

**Comment by marchorst** [comment]
> Now I had time to look at your changes. It looks very good, but I found some minor issues:
> 
> * Date fields now show the date additionally over the field (view birthday field within profiles)
> * Also the date now have the max width and not their special width as before
> * Within the event dialog the date and time fields are not separated anymore. Its now one field.
> * The red "required" bubble at checkbox fields will not be shown. View profile checkbox ** Ich willige in die Verarbeitung der Daten ein. **

- [x] Date fields now show the date additionally over the field (view birthday field within profiles)
- [x] The red "required" bubble at checkbox fields will not be shown. View profile checkbox ** Ich willige in die Verarbeitung der Daten ein. **
- [ ] Also the date now have the max width and not their special width as before
- [ ] Within the event dialog the date and time fields are not separated anymore. Its now one field.

What do you mean by the "special width"?

Will change the DateTime after my vacation.

**Comment by Fasse** [comment]
Date fields have a different width than the other fields. Now they have the same width as other fields. Maybe a class or something is missing, so that the css will not be used.

**Comment by Fasse** [comment]
I think we should use `data-provide=datepicker` so all date pickers will get the right length. I will than check if it's necessary that we still use `data-provide=datepicker-birthday`. But for now we should not use `data-provide=datepicker-birthday`.

**Comment by marchorst** [comment]
Everything should be fixed now.

**Review by Fasse — CHANGES_REQUESTED** [review]
The issues mentioned before are now all fixed. Thanks.

But while testing those bugfixes I found some more issues.

Before the captcha is shown I got the following error:
`/admidio/adm_my_files/templates/compile/55012bec073c77db07446c9ad713602b0574533d_0.file.form.captcha.tpl.php on line 24
row">
/admidio/adm_my_files/templates/compile/55012bec073c77db07446c9ad713602b0574533d_0.file.form.captcha.tpl.php on line 25
offset-sm-3 col-sm-9">`

Within the filter navbar there is a line skip at the date fields between the label and the field.

**Comment by marchorst** [comment]
Where did you test the Captcha field?

**Comment by Fasse** [comment]
I got the error at every captcha field. e.g. at registration. The exact error is shown in the screenshot:
grafik

**Comment by Fasse** [comment]
So there are three problems to resolve:

- [ ] error when showing captcha e.g. registration dialog
- [ ] within the filter navbar there is a line skip at the date fields between the label and the field
- [ ] update und installation dialog have problems with new smarty templates

**Comment by Fasse** [comment]
@marchorst are you still working on this feature? It would be nice to have that integrated.

**Comment by marchorst** [comment]
> @marchorst are you still working on this feature? It would be nice to have that integrated.

Yes, sorry for the delay! I had a lot of other stuff to do

**Comment by marchorst** [comment]
@Fasse can you please check again, it should be working now.

**Comment by Fasse** [comment]
Now everything works as expected :)

Thanks for your work!

**Pull request merged**
