### PR TITLE
Feature prepared statements

### LINKED ISSUE #244: Prepared Statements
https://secure.php.net/manual/de/pdo.prepared-statements.php

### PR DESCRIPTION
**Pull request by ximex**
fixes #244 
i plan for a later version (v4.0 or later) to use/change to: https://github.com/paragonie/easydb

There are some more improvements possible. Search for comment: `// TODO add more params`

### CODE REVIEW

**Comment by Fasse** [comment]
We should think about the placeholder. In my opinion ? will be not significant enough. We should to something like `#param#`, so its more visible.

**Comment by ximex** [comment]
@Fasse the `?` is the way to do it. The php interpreter looks for a `?`. See: https://secure.php.net/manual/de/pdo.prepared-statements.php

**Comment by ximex** [comment]
@Fasse fixed

**Comment by Fasse** [comment]
@ximex you can merge

**Comment by ximex** [comment]
@Fasse no changes of the `?` to `:name` etc?

**Comment by Fasse** [comment]
In my opinion we should. But maybe we merge and changed this later?!?

**Comment by ximex** [comment]
Ok. I look for this in v4.0

**Pull request merged**
