### PR TITLE
add and use new TABLE_PREFIX const

### PR DESCRIPTION
**Pull request by ximex**
So we need no global import any more and the table prefix should be a constant

### CODE REVIEW

**Comment by ximex** [comment]
@Fasse feel free to merge.

**Comment by ximex** [comment]
Should i also add:
- `$gDbType` => `DB_ENGINE` or `DB_TYPE`
- `$g_adm_src` => `DB_HOST` or `DB_DOMAIN`
- `$g_adm_port` => `DB_PORT`
- `$g_adm_db` => `DB_DATABASE` or `DB_NAME`
- `$g_adm_usr` => `DB_USERNAME`
- `$g_adm_pw` => `DB_PASSWORD`

**Comment by Fasse** [comment]
forget my last comment ...

**Comment by Fasse** [comment]
Hmm, we should not change the config.php.

**Pull request merged**
