### PR TITLE
211 deadline for participation

### PR DESCRIPTION
**Pull request by thomas-rcv**
Basic implementation from wilddom´s fork:

https://github.com/wilddom/admidio/commit/a22ca0eca6076095c395bb9f3d30b61f87b95fce

Adapted to current develop branch with adjustments.

### CODE REVIEW

**Comment by Fasse** [comment]
hmm maybe it is a problem with the event I already created. Because now this error also occurs if I open the event list.

**Comment by thomas-rcv** [comment]
Changed requests. Please have a look again.

**Comment by Fasse** [comment]
I have change this, so you can merge.

**Comment by thomas-rcv** [comment]
This was my first Intension as well. A simple bool check. But I´m not sure we might Need the date in future.
So to encapsulate this and also the date object comparison an preventing redunat code in several scripts was a ggod idea for me.
The on top bool check is great.

**Pull request merged**
