### PR TITLE
Feature android string resource

### PR DESCRIPTION
**Pull request by Fasse**
#68 #215

### CODE REVIEW

**Comment by Fasse** [comment]
@ximex review only needed for the language file classes

**Comment by thomas-rcv** [comment]
I would like to recommend to create a howto in our documentation for Plugin Developers.
Possible language files in Plugins also must be reworked.

**Comment by Fasse** [comment]
do you mean something like this: http://www.admidio.org/dokuwiki/doku.php?id=en:entwickler:how_to_make_your_plugin_translatable
;)

**Comment by thomas-rcv** [comment]
Hmm Looks not so bad. I think we could use it :D

**Comment by Fasse** [comment]
@ximex can i merge? Need this for other changes to language files.

**Comment by ximex** [comment]
checked and improve the code a little bit and rebased. if you are ok with my changes feel free to merge

**Comment by Fasse** [comment]
I have revert the structure of the languages.xml. This is not a translatable file and therefore we don't need the Android Recource String there. Also there were places in the code that were incompatible with the new format.

**Pull request merged**
