### PR TITLE
Feature improved dynamic language params

### PR DESCRIPTION
**Pull request by ximex**

### CODE REVIEW

**Comment by ximex** [comment]
see #583

**Comment by sirnone** [comment]
I don't like the possibility to use array or String - this makes this easy call complicated without an need for it!?

Just array would be better also vor readability i think.

**Comment by Fasse** [comment]
My opinion:
For compatibility we should allow string in 3.3 as well as array. But array should the favorit and in 4.0 we remove the string option.

Admidio core should also in 3.3 only use arrays.

**Comment by ximex** [comment]
Ok than i will change it that admidio uses only arrays intern but also support strings for backwards compatibility

**Comment by ximex** [comment]
@Fasse feel free to merge

**Pull request merged**
