### PR TITLE
refactor navigation class

### PR DESCRIPTION
**Pull request by ximex**
Is it really necessary to clear the url stack if you go to another module? (`$nav->addFirst(...)`)

### CODE REVIEW

**Comment by Fasse** [comment]
It was the easiest way to intialize the stack again. But if you have time to test you can change the handling so that we don't initialize the stack with every module.

**Comment by ximex** [comment]
not finished yet

**Comment by Fasse** [comment]
What is about this change request? Do you want to finish this?

**Comment by Fasse** [comment]
@ximex What's about this pull request?

**Pull request closed without merging**
