### PR TITLE
Feature dates list redesign

### PR DESCRIPTION
**Pull request by Fasse**
@thomas-rcv could you du a functional check

### CODE REVIEW

**Comment by thomas-rcv** [comment]
Sorry for my late response:

I got some undefined variables for date_view and sometimes for compact-table. In print mode with no matching dates also further notice. The text for option ical export is not matching.
Look at Screens below.
Generelly the implementation is quiet good, but I´m mot really happy with the printer output. A small formatted overview for a month,eg ... , I would fell more confident, like we have so far. We could think about the printers style sheet to improve, or additionally provide Excel export.
One Thing at the end ,... it would be great also outputing  the requested time period in print Output.

mozilla firefox_2015-11-13_23-16-16

**Comment by Fasse** [comment]
You Must make an Update then all notices Are gone.

**Comment by Fasse** [comment]
I have added a notice for the selected period to each print view and also made the print table more condensed. But I don't know what you mean with a small overview of a month or so. This issue was not to add a month view to the module. It only should add bootstrap style to the existing functionallity.

Please have a look at the implementation now. In my view we can merge this.

**Comment by thomas-rcv** [comment]
What I meant is the recordset is printed just on 1 page, like a Excel spreadsheet.
The bootstrap list is very large and you need further pages for printing.
Ok , not part of this issue

**Comment by thomas-rcv** [comment]
I fixed a unkown text key for Ical link.
The implemantation works fine.
From my side push it to master.

**Comment by Fasse** [comment]
#109

**Pull request merged**
