### PR TITLE
Refactor admFuncVariableIsValid

### PR DESCRIPTION
**Pull request by ximex**
please check if don't make a mistake.
i will push more commits to remove no longer used variables

### CODE REVIEW

**Comment by thomas-rcv** [comment]
Looks ok for me.
Please take into account this function is also used mostly plugins as well.
So eg. deleting 'numeric' would cause a lot of trouble.
If we plan fundamental changes here, we should inform the plugin developer before ddoing so.
No Problem in this pull request

**Comment by ximex** [comment]
I'm not planning to remove numeric ;-) maybe in a far future

**Comment by Fasse** [comment]
You have changed the boolean from 1, 0 to true, false but you dont have changed the calls within the scripts. This may be a problem.

**Comment by Fasse** [comment]
ok, works for me. 1 and 0 are still possible.

**Pull request merged**
