### PR TITLE
Replace mb_ereg_replace with preg_replace for php7.4 compatibility

### PR DESCRIPTION
**Pull request by schast**
Replace mb_ereg_replace with preg_replace in adm_program/system/classes/FileSystemUtils.php for php7.4 compatibility.

### CODE REVIEW

**Comment by Fasse** [comment]
@schast Thanks for your contribution. Could you shortly explain the problems mb_ereg_replace has with PHP 7.4

**Comment by schast** [comment]
@Fasse The database backup page (```/adm_program/modules/backup/backup.php```) only shows a white page.

Apache error.log:
```
2021-01-07T10:05:01.807404212Z  [Thu Jan 07 11:05:01.807235 2021] [php7:error] [pid 26] [client 172.21.11.2:41030]
PHP Fatal error:  Uncaught Error: Call to undefined function mb_ereg_replace() in /var/www/admidio/adm_program/system/classes/FileSystemUtils.php:1237
Stack trace:
    #0 /var/www/admidio/adm_program/modules/backup/backup.php(85): FileSystemUtils::removeInvalidCharsInFilename()
    #1 {main}\n  thrown in /var/www/admidio/adm_program/system/classes/FileSystemUtils.php on line 1237
```

Installed php Modules:
```
root@admidio:/var/www# dpkg -l | grep php
ii  libapache2-mod-php7.4         7.4.3-4ubuntu2.4                  amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  php-common                    2:75                              all          Common files for PHP packages
ii  php7.4                        7.4.3-4ubuntu2.4                  all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.4-cli                    7.4.3-4ubuntu2.4                  amd64        command-line interpreter for the PHP scripting language
ii  php7.4-common                 7.4.3-4ubuntu2.4                  amd64        documentation, examples and common module for PHP
ii  php7.4-gd                     7.4.3-4ubuntu2.4                  amd64        GD module for PHP
ii  php7.4-json                   7.4.3-4ubuntu2.4                  amd64        JSON module for PHP
ii  php7.4-mysql                  7.4.3-4ubuntu2.4                  amd64        MySQL module for PHP
ii  php7.4-opcache                7.4.3-4ubuntu2.4                  amd64        Zend OpCache module for PHP
ii  php7.4-pgsql                  7.4.3-4ubuntu2.4                  amd64        PostgreSQL module for PHP
ii  php7.4-readline               7.4.3-4ubuntu2.4                  amd64        readline module for PHP
ii  php7.4-xml                    7.4.3-4ubuntu2.4                  amd64        DOM, SimpleXML, XML, and XSL module for PHP
```

Installed apache Version:
```
root@admidio:/var/www# dpkg -l | grep apache
ii  apache2                       2.4.41-4ubuntu3.1                 amd64        Apache HTTP Server
ii  apache2-bin                   2.4.41-4ubuntu3.1                 amd64        Apache HTTP Server (modules and other binary files)
ii  apache2-data                  2.4.41-4ubuntu3.1                 all          Apache HTTP Server (common files)
ii  apache2-utils                 2.4.41-4ubuntu3.1                 amd64        Apache HTTP Server (utility programs for web servers)
ii  libapache2-mod-php7.4         7.4.3-4ubuntu2.4                  amd64        server-side, HTML-embedded scripting language (Apache 2 module)
```

**Comment by ximex** [comment]
this comes from the missing `php7.4-mbstring` package. I think we should make this as required in 4.1. This extension is recommended in this days with all the emojis and other multi byte characters

**Comment by Fasse** [comment]
ok, but the changes in this commit aren't wrong.

**Comment by ximex** [comment]
wrong is a hard word ;-)
for other mb_* functions we did it different: https://github.com/Admidio/admidio/blob/master/adm_program/system/classes/StringUtils.php#L21

**Comment by Fasse** [comment]
@ximex I'm not an expert in this case. What do you think is the better implementation. The previous one or this one?

**Pull request merged**
