### PR TITLE
reworked #203

### PR DESCRIPTION
**Pull request by thomas-rcv**
-parameters are passed within hidden fields now
- by the way fixed a bug: The list id initialzed with 0 as default by
function admFuncVariableisVald() occures SQL error because lists ids
starts with 1 and are count up.

### CODE REVIEW

**Comment by Fasse** [comment]
I found some other things to improve :)
- the new parameters `date_from`and `date_to` aren't documented in the head of lists_show.php.
- In my opinion we should change the navbar description from 

`Mitglieder dieser Gruppe im Zeitraum: Beginn [11.11.2015] Ende [31.12.2025]`

`Filter     Mitglieder im Zeitraum [11.11.2015] bis [11.11.2015]`

Filter is the name of the navbar that we used within the other navbars also. In the other part the text is shorter and the information isn't lost in my opinion. Also within the field date_from and date_to the default value should be only today. That is how the lists worked now. We don't want to show future members within the default. If you call a list you want to see who is now webmaster or in team 1.

**Comment by thomas-rcv** [comment]
Ok this would be minor changes.
How to do this now? Is it possible to change in the current opened pull request or is better to delete it and pull again?

**Comment by ximex** [comment]
you only have to create new commits on the same branch and push it to github. As long as the pullrequest isn't merged it works.

**Comment by Fasse** [comment]
Yes. Just code in your branch and make a commit. The pull request automatically has this new commit

**Comment by thomas-rcv** [comment]
Ok thanks. I guess will have finished tomorrow

**Comment by Fasse** [comment]
I have change the label of the date fields. Please have a look. If it's ok, we can merge.

**Comment by thomas-rcv** [comment]
Is ok for me. Feel Free to merge it

**Pull request merged**
