### PR TITLE
Feature mylist improvements

### PR DESCRIPTION
**Pull request by Fasse**
This pull request will address the following issues:
- Create mylists with many roles #171 
- firstname and lastname should be linked to profile in lists #124 
- Integrate HtmlForm class to MyList #61 
- Input data lost after send mylist form with missing field #25

### CODE REVIEW

**Comment by Fasse** [comment]
@ximex can you review this and have a look at travis. Still not found the relevant problems :(

**Comment by ximex** [comment]
its very easy to find the mistakes:
download: http://get.sensiolabs.org/php-cs-fixer.phar
execute: php php-cs-fixer.phar fix --config-file=".php_cs" --verbose --dry-run
or without `--dry-run` it would make the changes

**Comment by ximex** [comment]
should i merge this PR? i know the conflict and could do it

**Comment by Fasse** [comment]
yes you can

**Pull request merged**
